version: 0.2

phases:
  install:
    commands:
      - npm install
      - curl -sL $UP_BIN > up
      - curl -sL $UP_PROXY_BIN > /tmp/up-proxy
      - chmod +x /tmp/up-proxy up
  build:
    commands:
      - npm test
      - ./up
